### ISSUE TITLE
MediaInfo Extract会挂在Strm里面的MP4文件

### ISSUE THREAD

**Issue by stiffme** [sjtuross/StrmExtract#53]
用strm assistant的时候，如果扫描元数据(Mediainfo extract），贵插件似乎会发请求给xiaoya挂在真正的MP4文件，比如：

```shell
2024-12-28 19:02:52.254 Info Strm Assistant: MediaInfoPersist - Serialization Skipped (No MediaInfo): /media/strmJson/media/每日更新/电视剧/国产剧/风中的火焰 (2024)/Season 1/风中的火焰.S01E21-mediainfo.json
2024-12-28 19:02:52.254 Info Strm Assistant: MediaInfoExtract - Progress 20/163282 - Task 20: /media/每日更新/电视剧/国产剧/风中的火焰 (2024)/Season 1/风中的火焰.S01E21.strm
2024-12-28 19:02:52.660 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/20.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-12-28 19:02:52.671 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-12-28 19:02:52.672 Error App: Error in ffprobe
        *** Error Report ***
        Version: 4.8.10.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #72806 SMP Thu Sep 5 13:44:44 CST 2024
        Framework: .NET 6.0.31
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/20.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
        ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
          built with gcc 10.3.0 (crosstool-NG 1.25.0)
        [mov,mp4,m4a,3gp,3g2,mj2 @ 0x25f1940] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
        [mov,mp4,m4a,3gp,3g2,mj2 @ 0x25f1940] moov atom not found
        http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/20.mp4: Invalid data found when processing input


        {

        }
           at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
           at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
        Source: Emby.Server.MediaEncoding
        TargetSite: Void MoveNext()

2024-12-28 19:02:52.701 Info Strm Assistant: MediaInfoPersist - Serialization Skipped (No MediaInfo): /media/strmJson/media/每日更新/电视剧/国产剧/风中的火焰 (2024)/Season 1/风中的火焰.S01E20-mediainfo.json
2024-12-28 19:02:52.701 Info Strm Assistant: MediaInfoExtract - Progress 21/163282 - Task 21: /media/每日更新/电视剧/国产剧/风中的火焰 (2024)/Season 1/风中的火焰.S01E20.strm
2024-12-28 19:02:53.106 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://xiaoya.host:5678/d/每日更新/电视剧/美剧/石油天王/石油天王.S01E09.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-12-28 19:02:53.117 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-12-28 19:02:53.118 Error App: Error in ffprobe
        *** Error Report ***
        Version: 4.8.10.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #72806 SMP Thu Sep 5 13:44:44 CST 2024
        Framework: .NET 6.0.31
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "http://xiaoya.host:5678/d/每日更新/电视剧/美剧/石油天王/石油天王.S01E09.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
        ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
          built with gcc 10.3.0 (crosstool-NG 1.25.0)
        [matroska,webm @ 0x1249940] Format matroska,webm detected only with low score of 1, misdetection possible!
        Truncating packet of size 9071 to 49
        [matroska,webm @ 0x1249940] EBML header parsing failed
        http://xiaoya.host:5678/d/每日更新/电视剧/美剧/石油天王/石油天王.S01E09.mkv: Invalid data found when processing input


        {

        }
           at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
           at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
        Source: Emby.Server.MediaEncoding
        TargetSite: Void MoveNext()

2024-12-28 19:02:53.121 Info HttpClient: GET https://api.themoviedb.org/3/tv/157741/season/1/episode/9?api_key=‌f6bd687ffa63cd282b6ff2c6877f2669‌&append_to_response=images,external_ids,credits,videos&language=zh-CN&include_image_language=zh-CN,zh,null
2024-12-28 19:02:53.474 Info HttpClient: GET https://api.themoviedb.org/3/tv/157741/season/1/episode/9?api_key=‌f6bd687ffa63cd282b6ff2c6877f2669‌&append_to_response=images,external_ids,credits,videos
2024-12-28 19:02:54.813 Info Strm Assistant: MediaInfoPersist - Serialization Skipped (No MediaInfo): /media/strmJson/media/每日更新/电视剧/美剧/石油天王 (2024)/Season 1/石油天王 - S01E09 - 狼营-mediainfo.json
2024-12-28 19:02:54.813 Info Strm Assistant: MediaInfoExtract - Progress 22/163282 - Task 22: /media/每日更新/电视剧/美剧/石油天王 (2024)/Season 1/石油天王 - S01E09 - 狼营.strm
2024-12-28 19:02:55.229 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://xiaoya.host:5678/d/每日更新/电视剧/美剧/传奇办公室/The.Agency.2024.S01E07.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-12-28 19:02:55.245 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-12-28 19:02:55.246 Error App: Error in ffprobe
        *** Error Report ***
        Version: 4.8.10.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #72806 SMP Thu Sep 5 13:44:44 CST 2024
        Framework: .NET 6.0.31
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "http://xiaoya.host:5678/d/每日更新/电视剧/美剧/传奇办公室/The.Agency.2024.S01E07.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
        ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
          built with gcc 10.3.0 (crosstool-NG 1.25.0)
        [matroska,webm @ 0x979940] Format matroska,webm detected only with low score of 1, misdetection possible!
        Truncating packet of size 9071 to 49
        [matroska,webm @ 0x979940] EBML header parsing failed
        http://xiaoya.host:5678/d/每日更新/电视剧/美剧/传奇办公室/The.Agency.2024.S01E07.mkv: Invalid data found when processing input


        {

        }
           at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
           at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
        Source: Emby.Server.MediaEncoding
        TargetSite: Void MoveNext()

2024-12-28 19:02:55.247 Info HttpClient: GET https://api.themoviedb.org/3/tv/219971/season/1/episode/7?api_key=‌f6bd687ffa63cd282b6ff2c6877f2669‌&append_to_response=images,external_ids,credits,videos&language=zh-CN&include_image_language=zh-CN,zh,null
2024-12-28 19:02:55.691 Info HttpClient: GET https://api.themoviedb.org/3/tv/219971/season/1/episode/7?api_key=‌f6bd687ffa63cd282b6ff2c6877f2669‌&append_to_response=images,external_ids,credits,videos&language=en-US&include_image_language=en-US,null
2024-12-28 19:02:55.791 Info HttpClient: GET https://api.themoviedb.org/3/tv/219971/season/1/episode/7?api_key=‌f6bd687ffa63cd282b6ff2c6877f2669‌&append_to_response=images,external_ids,credits,videos
2024-12-28 19:02:55.985 Info Strm Assistant: MediaInfoPersist - Serialization Skipped (No MediaInfo): /media/strmJson/media/每日更新/电视剧/美剧/传奇办公室 (2024)/Season 1/传奇办公室 - S01E07 - 第 7 集-mediainfo.json
2024-12-28 19:02:55.986 Info Strm Assistant: MediaInfoExtract - Progress 23/163282 - Task 23: /media/每日更新/电视剧/美剧/传奇办公室 (2024)/Season 1/传奇办公室 - S01E07 - 第 7 集.strm
2024-12-28 19:02:56.393 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/19.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-12-28 19:02:56.404 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
2024-12-28 19:02:56.405 Error App: Error in ffprobe
        *** Error Report ***
        Version: 4.8.10.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #72806 SMP Thu Sep 5 13:44:44 CST 2024
        Framework: .NET 6.0.31
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/19.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
        ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
          built with gcc 10.3.0 (crosstool-NG 1.25.0)
        [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb7d940] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
        [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb7d940] moov atom not found
        http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/19.mp4: Invalid data found when processing input


        {

        }
           at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
           at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
        Source: Emby.Server.MediaEncoding
        TargetSite: Void MoveNext()

2024-12-28 19:02:56.425 Info Strm Assistant: MediaInfoPersist - Serialization Skipped (No MediaInfo): /media/strmJson/media/每日更新/电视剧/国产剧/风中的火焰 (2024)/Season 1/风中的火焰 - S01E19 - 第 19 集-mediainfo.json
2024-12-28 19:02:56.425 Info Strm Assistant: MediaInfoExtract - Progress 24/163282 - Task 24: /media/每日更新/电视剧/国产剧/风中的火焰 (2024)/Season 1/风中的火焰 - S01E19 - 第 19 集.strm
2024-12-28 19:02:56.835 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i "http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/风中的火焰/18.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2024-12-28 19:02:56.846 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded
bash
```
请问有办法只扫描Strm文件，而不需要挂在真正的mp4文件吗？
谢谢

**Comment by sjtuross** [comment]
媒体信息来自视频文件本身，需要读几秒获得，单纯strm就一个文本文件。

**Comment by stiffme** [comment]
谢谢，那如果已经存在了同名的nfo文件，是否就可以直接跳过读取视频几秒？

**Comment by sjtuross** [comment]
nfo是元数据而非媒体信息。你如果不清楚媒体信息的作用，那没必要扫，不是必须的。

**Comment by stiffme** [comment]
好的谢谢啦，我目前改成了只扫描最爱标记的几个。全库扫描有点太慢了。
